### ISSUE TITLE
Code does not run

### ISSUE THREAD

**Issue by schmiflo** [him1411/edgar10q-dataset#1]
I tried to re-create your dataset but struggle with the codebase.

What exactly do `DONE_LIST` and `DONE_COMP` refer to? Also these imports seem to come from the wrong file https://github.com/him1411/edgar10q-dataset/blob/9a2c4c415ff3ba336385402eec940ac1195ca329/xbrl_scraper.py#L7

Since the dataset is cast as a significant contribution, it would be awesome if a shell script was available to re-create the data. At least dedicated `main` functions in the scripts would help a lot.

**Comment by him1411** [comment]
hi @schmiflo. We have updated the code and added the new link containing the dataset. Please check it out. Apologies for the late response.
